namespace: plattformsikkerhet
team: plattformsikkerhet
ingresses:
  - https://dingser.prod-gcp.nais.io
env:
  - name: APPLICATION_PROFILE
    value: PROD
  - name: APPLICATION_REDIRECT_URL
    value: "https://dingser.prod-gcp.nais.io/oauth"
  - name: IDPORTEN_WELLKNOWN
    value: "https://oidc.difi.no/idporten-oidc-provider/.well-known/openid-configuration"
  - name: TOKENDINGS_WELLKNOWN
    value: "https://tokendings.prod-gcp.nais.io/.well-known/oauth-authorization-server"
  - name: CLIENT_GCP_AUDIENCE
    value: prod-gcp:plattformsikkerhet:dings-validate
  - name: CLIENT_ONPREM_AUDIENCE
    value: prod-fss:plattformsikkerhet:dings-onprem-test
  - name: DOWNTSTREAM_GCP_API_URL
    value: "https://dings-validate.prod-gcp.nais.io/hello"
  - name: DOWNTSTREAM_ONPREM_API_URL
    value: "https://dings-onprem-test.adeo.no/hello"
replicas:
  min: 1
  max: 1
outbound-host:
  - oidc.difi.no
  - tokendings.prod-gcp.nais.io
  - dings-validate.prod-gcp.nais.io
  - dings-onprem-test.adeo.no
